version: "3.9"  # optional since v1.27.0
services:
  mysql:
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:8.0.33
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_USER=weeb
      - MYSQL_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=weeb
    volumes:
      - 'weeb-user-serivce_db:/var/lib/mysql'
    networks:
      - weeb-user-service-network
  
  minio:
    image: minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9001"
    volumes:
      - 'minio_data:/data'
    networks:
      weeb-user-service-network:
        aliases:
          - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-setup:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO to be ready...';
      /usr/bin/mc alias set minio http://minio:9000 minio minio123;
      /usr/bin/mc mb minio/anime --ignore-existing;
      echo 'MinIO bucket anime created successfully!';
      "
    networks:
      - weeb-user-service-network
  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_MULTIPLE_DATABASES=auth,user
    volumes:
      - 'postgres_db:/var/lib/postgresql/data/'
      - '.db_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql'
    networks:
      weeb-user-service-network:
  key_management_service_migration:
    image: fossapps/key-management-service
    command:
      - ./key-management-service
      - db
      - migrate
    environment:
      - DatabaseConfig__Host=postgres
      - DatabaseConfig__Port=5432
      - DatabaseConfig__Database=auth
      - ASPNETCORE_URLS=http://+:5001
      - DatabaseConfig__MigrationTableName=__migrations_key_management
      - DatabaseConfig__Password=mysecretpassword
      - DatabaseConfig__User=postgres
    networks:
      weeb-user-service-network:
    depends_on:
      - postgres
  key_management_service:
    image: fossapps/key-management-service
    ports:
      - '5001:5001'
    environment:
      - DatabaseConfig__Host=postgres
      - DatabaseConfig__Port=5432
      - DatabaseConfig__Database=auth
      - ASPNETCORE_URLS=http://+:5001
      - DatabaseConfig__MigrationTableName=__migrations_key_management
      - DatabaseConfig__Password=mysecretpassword
      - DatabaseConfig__User=postgres
    depends_on:
      - postgres
    networks:
      weeb-user-service-network:
volumes:
  weeb-user-serivce_db:
  minio_data:
  postgres_db:

networks:
  weeb-user-service-network:
