package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/weeb-vip/user-service/graph/generated"
	"github.com/weeb-vip/user-service/graph/model"
	"github.com/weeb-vip/user-service/internal/resolvers"
)

// CreatUser is the resolver for the CreatUser field.
func (r *mutationResolver) CreatUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	return resolvers.CreateUser(ctx, r.UserService, &input)
}

// UpdateUserDetails is the resolver for the UpdateUserDetails field.
func (r *mutationResolver) UpdateUserDetails(ctx context.Context, input model.UpdateUserInput) (*model.User, error) {
	return resolvers.UpdateUser(ctx, r.UserService, &input)
}

// UploadProfileImage is the resolver for the UploadProfileImage field.
func (r *mutationResolver) UploadProfileImage(ctx context.Context, image graphql.Upload) (*model.User, error) {
	return resolvers.UploadProfileImage(ctx, r.UserService, r.ImageService, image)
}

// UploadBannerImage is the resolver for the UploadBannerImage field.
func (r *mutationResolver) UploadBannerImage(ctx context.Context, image graphql.Upload) (*model.User, error) {
	return resolvers.UploadBannerImage(ctx, r.UserService, r.ImageService, image)
}

// Follow is the resolver for the follow field.
func (r *mutationResolver) Follow(ctx context.Context, userID string) (model.FollowStatus, error) {
	return resolvers.Follow(ctx, r.FollowsService, userID)
}

// Unfollow is the resolver for the unfollow field.
func (r *mutationResolver) Unfollow(ctx context.Context, userID string) (bool, error) {
	return resolvers.Unfollow(ctx, r.FollowsService, userID)
}

// AcceptFollowRequest is the resolver for the acceptFollowRequest field.
func (r *mutationResolver) AcceptFollowRequest(ctx context.Context, followerID string) (bool, error) {
	return resolvers.AcceptFollowRequest(ctx, r.FollowsService, followerID)
}

// DeclineFollowRequest is the resolver for the declineFollowRequest field.
func (r *mutationResolver) DeclineFollowRequest(ctx context.Context, followerID string) (bool, error) {
	return resolvers.DeclineFollowRequest(ctx, r.FollowsService, followerID)
}

// RemoveFollower is the resolver for the removeFollower field.
func (r *mutationResolver) RemoveFollower(ctx context.Context, followerID string) (bool, error) {
	return resolvers.RemoveFollower(ctx, r.FollowsService, followerID)
}

// UserDetails is the resolver for the UserDetails field.
func (r *queryResolver) UserDetails(ctx context.Context) (*model.User, error) {
	return resolvers.GetUser(ctx, r.UserService)
}

// UserByUsername is the resolver for the userByUsername field.
func (r *queryResolver) UserByUsername(ctx context.Context, username string) (*model.PublicUser, error) {
	return resolvers.UserByUsername(ctx, r.UserService, username)
}

// PublicUserByID is the resolver for the publicUserByID field.
func (r *queryResolver) PublicUserByID(ctx context.Context, id string) (*model.PublicUser, error) {
	return resolvers.PublicUserByID(ctx, r.UserService, id)
}

// Followers is the resolver for the followers field.
func (r *queryResolver) Followers(ctx context.Context, userID string, page int, limit int) (*model.PublicUserPaginated, error) {
	return resolvers.Followers(ctx, r.FollowsService, userID, page, limit)
}

// Following is the resolver for the following field.
func (r *queryResolver) Following(ctx context.Context, userID string, page int, limit int) (*model.PublicUserPaginated, error) {
	return resolvers.Following(ctx, r.FollowsService, userID, page, limit)
}

// FollowRequests is the resolver for the followRequests field.
func (r *queryResolver) FollowRequests(ctx context.Context, page int, limit int) (*model.PublicUserPaginated, error) {
	return resolvers.FollowRequests(ctx, r.FollowsService, page, limit)
}

// FollowerIDs is the resolver for the followerIDs field.
func (r *queryResolver) FollowerIDs(ctx context.Context, userID string, after *string, limit int) ([]string, error) {
	return resolvers.FollowerIDs(ctx, r.FollowsService, userID, after, limit)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
