package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"

	"github.com/weeb-vip/user-service/graph/generated"
	"github.com/weeb-vip/user-service/graph/model"
	"github.com/weeb-vip/user-service/internal/resolvers"
)

// FollowerCount is the resolver for the followerCount field.
func (r *publicUserResolver) FollowerCount(ctx context.Context, obj *model.PublicUser) (int, error) {
	followers, _, err := resolvers.PublicUserCounts(ctx, r.FollowsService, obj.ID)

	return followers, err
}

// FollowingCount is the resolver for the followingCount field.
func (r *publicUserResolver) FollowingCount(ctx context.Context, obj *model.PublicUser) (int, error) {
	_, following, err := resolvers.PublicUserCounts(ctx, r.FollowsService, obj.ID)

	return following, err
}

// ViewerFollowStatus is the resolver for the viewerFollowStatus field.
func (r *publicUserResolver) ViewerFollowStatus(ctx context.Context, obj *model.PublicUser) (model.FollowStatus, error) {
	return resolvers.PublicUserViewerFollowStatus(ctx, r.FollowsService, obj.ID)
}

// PublicUser returns generated.PublicUserResolver implementation.
func (r *Resolver) PublicUser() generated.PublicUserResolver { return &publicUserResolver{r} }

type publicUserResolver struct{ *Resolver }
