ALTER TABLE users DROP COLUMN IF EXISTS lists_public;
ALTER TABLE users DROP COLUMN IF EXISTS accent_color;
ALTER TABLE users DROP COLUMN IF EXISTS bio;
ALTER TABLE users DROP COLUMN IF EXISTS banner_image_url;
