// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/services/follows/repositories/follows.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	models "github.com/weeb-vip/user-service/internal/services/follows/models"
	models0 "github.com/weeb-vip/user-service/internal/services/users/models"
	gorm "gorm.io/gorm"
)

// MockFollowsRepository is a mock of FollowsRepository interface.
type MockFollowsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFollowsRepositoryMockRecorder
}

// MockFollowsRepositoryMockRecorder is the mock recorder for MockFollowsRepository.
type MockFollowsRepositoryMockRecorder struct {
	mock *MockFollowsRepository
}

// NewMockFollowsRepository creates a new mock instance.
func NewMockFollowsRepository(ctrl *gomock.Controller) *MockFollowsRepository {
	mock := &MockFollowsRepository{ctrl: ctrl}
	mock.recorder = &MockFollowsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFollowsRepository) EXPECT() *MockFollowsRepositoryMockRecorder {
	return m.recorder
}

// Accept mocks base method.
func (m *MockFollowsRepository) Accept(ctx context.Context, tx *gorm.DB, followerID, followeeID string, at time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Accept", ctx, tx, followerID, followeeID, at)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Accept indicates an expected call of Accept.
func (mr *MockFollowsRepositoryMockRecorder) Accept(ctx, tx, followerID, followeeID, at interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accept", reflect.TypeOf((*MockFollowsRepository)(nil).Accept), ctx, tx, followerID, followeeID, at)
}

// Counts mocks base method.
func (m *MockFollowsRepository) Counts(ctx context.Context, userID string) (models.Counts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Counts", ctx, userID)
	ret0, _ := ret[0].(models.Counts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Counts indicates an expected call of Counts.
func (mr *MockFollowsRepositoryMockRecorder) Counts(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Counts", reflect.TypeOf((*MockFollowsRepository)(nil).Counts), ctx, userID)
}

// Create mocks base method.
func (m *MockFollowsRepository) Create(ctx context.Context, tx *gorm.DB, follow *models.UserFollow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, follow)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFollowsRepositoryMockRecorder) Create(ctx, tx, follow interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFollowsRepository)(nil).Create), ctx, tx, follow)
}

// Delete mocks base method.
func (m *MockFollowsRepository) Delete(ctx context.Context, tx *gorm.DB, followerID, followeeID string, status models.Status) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tx, followerID, followeeID, status)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockFollowsRepositoryMockRecorder) Delete(ctx, tx, followerID, followeeID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFollowsRepository)(nil).Delete), ctx, tx, followerID, followeeID, status)
}

// FollowerIDs mocks base method.
func (m *MockFollowsRepository) FollowerIDs(ctx context.Context, followeeID, after string, limit int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FollowerIDs", ctx, followeeID, after, limit)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FollowerIDs indicates an expected call of FollowerIDs.
func (mr *MockFollowsRepositoryMockRecorder) FollowerIDs(ctx, followeeID, after, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FollowerIDs", reflect.TypeOf((*MockFollowsRepository)(nil).FollowerIDs), ctx, followeeID, after, limit)
}

// Get mocks base method.
func (m *MockFollowsRepository) Get(ctx context.Context, followerID, followeeID string) (*models.UserFollow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, followerID, followeeID)
	ret0, _ := ret[0].(*models.UserFollow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockFollowsRepositoryMockRecorder) Get(ctx, followerID, followeeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFollowsRepository)(nil).Get), ctx, followerID, followeeID)
}

// ListFollowers mocks base method.
func (m *MockFollowsRepository) ListFollowers(ctx context.Context, followeeID string, status models.Status, page, limit int) ([]*models0.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFollowers", ctx, followeeID, status, page, limit)
	ret0, _ := ret[0].([]*models0.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListFollowers indicates an expected call of ListFollowers.
func (mr *MockFollowsRepositoryMockRecorder) ListFollowers(ctx, followeeID, status, page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFollowers", reflect.TypeOf((*MockFollowsRepository)(nil).ListFollowers), ctx, followeeID, status, page, limit)
}

// ListFollowing mocks base method.
func (m *MockFollowsRepository) ListFollowing(ctx context.Context, followerID string, status models.Status, page, limit int) ([]*models0.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFollowing", ctx, followerID, status, page, limit)
	ret0, _ := ret[0].([]*models0.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListFollowing indicates an expected call of ListFollowing.
func (mr *MockFollowsRepositoryMockRecorder) ListFollowing(ctx, followerID, status, page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFollowing", reflect.TypeOf((*MockFollowsRepository)(nil).ListFollowing), ctx, followerID, status, page, limit)
}

// Transaction mocks base method.
func (m *MockFollowsRepository) Transaction(ctx context.Context, fn func(*gorm.DB) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transaction indicates an expected call of Transaction.
func (mr *MockFollowsRepositoryMockRecorder) Transaction(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockFollowsRepository)(nil).Transaction), ctx, fn)
}
