// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/services/follows/interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	follows "github.com/weeb-vip/user-service/internal/services/follows"
	models "github.com/weeb-vip/user-service/internal/services/follows/models"
	models0 "github.com/weeb-vip/user-service/internal/services/users/models"
	gorm "gorm.io/gorm"
)

// MockFollows is a mock of Follows interface.
type MockFollows struct {
	ctrl     *gomock.Controller
	recorder *MockFollowsMockRecorder
}

// MockFollowsMockRecorder is the mock recorder for MockFollows.
type MockFollowsMockRecorder struct {
	mock *MockFollows
}

// NewMockFollows creates a new mock instance.
func NewMockFollows(ctrl *gomock.Controller) *MockFollows {
	mock := &MockFollows{ctrl: ctrl}
	mock.recorder = &MockFollowsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFollows) EXPECT() *MockFollowsMockRecorder {
	return m.recorder
}

// Accept mocks base method.
func (m *MockFollows) Accept(ctx context.Context, ownerID, followerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Accept", ctx, ownerID, followerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Accept indicates an expected call of Accept.
func (mr *MockFollowsMockRecorder) Accept(ctx, ownerID, followerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accept", reflect.TypeOf((*MockFollows)(nil).Accept), ctx, ownerID, followerID)
}

// Counts mocks base method.
func (m *MockFollows) Counts(ctx context.Context, userID string) (models.Counts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Counts", ctx, userID)
	ret0, _ := ret[0].(models.Counts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Counts indicates an expected call of Counts.
func (mr *MockFollowsMockRecorder) Counts(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Counts", reflect.TypeOf((*MockFollows)(nil).Counts), ctx, userID)
}

// Decline mocks base method.
func (m *MockFollows) Decline(ctx context.Context, ownerID, followerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decline", ctx, ownerID, followerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Decline indicates an expected call of Decline.
func (mr *MockFollowsMockRecorder) Decline(ctx, ownerID, followerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decline", reflect.TypeOf((*MockFollows)(nil).Decline), ctx, ownerID, followerID)
}

// Follow mocks base method.
func (m *MockFollows) Follow(ctx context.Context, viewerID, targetID string) (follows.ViewerStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Follow", ctx, viewerID, targetID)
	ret0, _ := ret[0].(follows.ViewerStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Follow indicates an expected call of Follow.
func (mr *MockFollowsMockRecorder) Follow(ctx, viewerID, targetID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Follow", reflect.TypeOf((*MockFollows)(nil).Follow), ctx, viewerID, targetID)
}

// FollowerIDs mocks base method.
func (m *MockFollows) FollowerIDs(ctx context.Context, userID, after string, limit int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FollowerIDs", ctx, userID, after, limit)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FollowerIDs indicates an expected call of FollowerIDs.
func (mr *MockFollowsMockRecorder) FollowerIDs(ctx, userID, after, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FollowerIDs", reflect.TypeOf((*MockFollows)(nil).FollowerIDs), ctx, userID, after, limit)
}

// Followers mocks base method.
func (m *MockFollows) Followers(ctx context.Context, viewerID *string, userID string, page, limit int) (follows.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Followers", ctx, viewerID, userID, page, limit)
	ret0, _ := ret[0].(follows.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Followers indicates an expected call of Followers.
func (mr *MockFollowsMockRecorder) Followers(ctx, viewerID, userID, page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Followers", reflect.TypeOf((*MockFollows)(nil).Followers), ctx, viewerID, userID, page, limit)
}

// Following mocks base method.
func (m *MockFollows) Following(ctx context.Context, viewerID *string, userID string, page, limit int) (follows.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Following", ctx, viewerID, userID, page, limit)
	ret0, _ := ret[0].(follows.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Following indicates an expected call of Following.
func (mr *MockFollowsMockRecorder) Following(ctx, viewerID, userID, page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Following", reflect.TypeOf((*MockFollows)(nil).Following), ctx, viewerID, userID, page, limit)
}

// RemoveFollower mocks base method.
func (m *MockFollows) RemoveFollower(ctx context.Context, ownerID, followerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFollower", ctx, ownerID, followerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFollower indicates an expected call of RemoveFollower.
func (mr *MockFollowsMockRecorder) RemoveFollower(ctx, ownerID, followerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFollower", reflect.TypeOf((*MockFollows)(nil).RemoveFollower), ctx, ownerID, followerID)
}

// Requests mocks base method.
func (m *MockFollows) Requests(ctx context.Context, ownerID string, page, limit int) (follows.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Requests", ctx, ownerID, page, limit)
	ret0, _ := ret[0].(follows.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Requests indicates an expected call of Requests.
func (mr *MockFollowsMockRecorder) Requests(ctx, ownerID, page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Requests", reflect.TypeOf((*MockFollows)(nil).Requests), ctx, ownerID, page, limit)
}

// Unfollow mocks base method.
func (m *MockFollows) Unfollow(ctx context.Context, viewerID, targetID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unfollow", ctx, viewerID, targetID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unfollow indicates an expected call of Unfollow.
func (mr *MockFollowsMockRecorder) Unfollow(ctx, viewerID, targetID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unfollow", reflect.TypeOf((*MockFollows)(nil).Unfollow), ctx, viewerID, targetID)
}

// ViewerStatus mocks base method.
func (m *MockFollows) ViewerStatus(ctx context.Context, viewerID *string, targetID string) (follows.ViewerStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ViewerStatus", ctx, viewerID, targetID)
	ret0, _ := ret[0].(follows.ViewerStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ViewerStatus indicates an expected call of ViewerStatus.
func (mr *MockFollowsMockRecorder) ViewerStatus(ctx, viewerID, targetID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewerStatus", reflect.TypeOf((*MockFollows)(nil).ViewerStatus), ctx, viewerID, targetID)
}

// MockEventWriter is a mock of EventWriter interface.
type MockEventWriter struct {
	ctrl     *gomock.Controller
	recorder *MockEventWriterMockRecorder
}

// MockEventWriterMockRecorder is the mock recorder for MockEventWriter.
type MockEventWriterMockRecorder struct {
	mock *MockEventWriter
}

// NewMockEventWriter creates a new mock instance.
func NewMockEventWriter(ctrl *gomock.Controller) *MockEventWriter {
	mock := &MockEventWriter{ctrl: ctrl}
	mock.recorder = &MockEventWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventWriter) EXPECT() *MockEventWriterMockRecorder {
	return m.recorder
}

// Write mocks base method.
func (m *MockEventWriter) Write(ctx context.Context, tx *gorm.DB, subject, id string, payload any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", ctx, tx, subject, id, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockEventWriterMockRecorder) Write(ctx, tx, subject, id, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockEventWriter)(nil).Write), ctx, tx, subject, id, payload)
}

// MockUserLookup is a mock of UserLookup interface.
type MockUserLookup struct {
	ctrl     *gomock.Controller
	recorder *MockUserLookupMockRecorder
}

// MockUserLookupMockRecorder is the mock recorder for MockUserLookup.
type MockUserLookupMockRecorder struct {
	mock *MockUserLookup
}

// NewMockUserLookup creates a new mock instance.
func NewMockUserLookup(ctrl *gomock.Controller) *MockUserLookup {
	mock := &MockUserLookup{ctrl: ctrl}
	mock.recorder = &MockUserLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserLookup) EXPECT() *MockUserLookupMockRecorder {
	return m.recorder
}

// GetUserDetails mocks base method.
func (m *MockUserLookup) GetUserDetails(ctx context.Context, id string) (*models0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserDetails", ctx, id)
	ret0, _ := ret[0].(*models0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserDetails indicates an expected call of GetUserDetails.
func (mr *MockUserLookupMockRecorder) GetUserDetails(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserDetails", reflect.TypeOf((*MockUserLookup)(nil).GetUserDetails), ctx, id)
}
